# Generated by Django 3.1.3 on 2021-07-20 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tade", "0053_taggregationhastag_depth"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoryFilter",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="MatchFilter",
            fields=[
                (
                    "storyfilter_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tade.storyfilter",
                    ),
                ),
                ("match_string", models.TextField()),
                ("is_regexp", models.BooleanField(default=False)),
            ],
            bases=("tade.storyfilter",),
        ),
        migrations.AddField(
            model_name="taggregationhastag",
            name="exclude_filters",
            field=models.ManyToManyField(
                blank=True, related_name="excluded_in", to="tade.StoryFilter"
            ),
        ),
        migrations.AddField(
            model_name="taggregationhastag",
            name="include_filters",
            field=models.ManyToManyField(
                blank=True, related_name="included_in", to="tade.StoryFilter"
            ),
        ),
        migrations.CreateModel(
            name="DomainFilter",
            fields=[
                (
                    "matchfilter_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tade.matchfilter",
                    ),
                ),
            ],
            bases=("tade.matchfilter",),
        ),
        migrations.CreateModel(
            name="TagNameFilter",
            fields=[
                (
                    "matchfilter_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tade.matchfilter",
                    ),
                ),
            ],
            bases=("tade.matchfilter",),
        ),
        migrations.CreateModel(
            name="UserFilter",
            fields=[
                (
                    "storyfilter_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tade.storyfilter",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=("tade.storyfilter",),
        ),
        migrations.CreateModel(
            name="ExactTagFilter",
            fields=[
                (
                    "storyfilter_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tade.storyfilter",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tade.tag",
                    ),
                ),
            ],
            bases=("tade.storyfilter",),
        ),
        migrations.DeleteModel(
            name="TagFilter",
        ),
    ]
